// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsn4iBK2vCw7v4NQClXVUzNRfOc0cI0TU',
    appId: '1:891287379773:web:66f649cae9e3f91add6f54',
    messagingSenderId: '891287379773',
    projectId: 'psychiatriststartup',
    authDomain: 'psychiatriststartup.firebaseapp.com',
    storageBucket: 'psychiatriststartup.appspot.com',
    measurementId: 'G-JNQZ4J6BTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTJvfD_sXkkFGT2HbSLWm64LIYCup9lNc',
    appId: '1:891287379773:android:badcc092b9bec15bdd6f54',
    messagingSenderId: '891287379773',
    projectId: 'psychiatriststartup',
    storageBucket: 'psychiatriststartup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiZLFbE5YYcNjotyvy6gsbhjcD0v7AY38',
    appId: '1:891287379773:ios:1b6fa53508ee58cbdd6f54',
    messagingSenderId: '891287379773',
    projectId: 'psychiatriststartup',
    storageBucket: 'psychiatriststartup.appspot.com',
    iosBundleId: 'com.example.mentalheathstartup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiZLFbE5YYcNjotyvy6gsbhjcD0v7AY38',
    appId: '1:891287379773:ios:1b6fa53508ee58cbdd6f54',
    messagingSenderId: '891287379773',
    projectId: 'psychiatriststartup',
    storageBucket: 'psychiatriststartup.appspot.com',
    iosBundleId: 'com.example.mentalheathstartup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsn4iBK2vCw7v4NQClXVUzNRfOc0cI0TU',
    appId: '1:891287379773:web:d8ec25f986f4bcefdd6f54',
    messagingSenderId: '891287379773',
    projectId: 'psychiatriststartup',
    authDomain: 'psychiatriststartup.firebaseapp.com',
    storageBucket: 'psychiatriststartup.appspot.com',
    measurementId: 'G-165TJ2L1Y8',
  );
}
